// <auto-generated />
using CarMvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20231231203823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CarMvc.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1.3999999999999999,
                            Model = "Octavia",
                            Motor = "Benzyna",
                            OrganizationId = 1,
                            Power = 100,
                            Priority = 3,
                            Producer = "Skoda",
                            RegistrationNumber = "ABC123"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1.3999999999999999,
                            Model = "A3",
                            Motor = "Benzyna",
                            OrganizationId = 2,
                            Power = 100,
                            Priority = 3,
                            Producer = "Audi",
                            RegistrationNumber = "DEF456"
                        });
                });

            modelBuilder.Entity("Core.Models.Address", b =>
                {
                    b.Property<int>("AdrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdrId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Core.Models.Organization", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrgId");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            OrgId = 1,
                            NIP = "1234567890",
                            Name = "Organizacja A"
                        },
                        new
                        {
                            OrgId = 2,
                            NIP = "0987654321",
                            Name = "Organizacja B"
                        });
                });

            modelBuilder.Entity("CarMvc.Models.Car", b =>
                {
                    b.HasOne("Core.Models.Organization", "Owner")
                        .WithOne("car")
                        .HasForeignKey("CarMvc.Models.Car", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Core.Models.Address", b =>
                {
                    b.HasOne("Core.Models.Organization", "Organization")
                        .WithOne("Address")
                        .HasForeignKey("Core.Models.Address", "AdrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Core.Models.Organization", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("car")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
